### ISSUE TITLE
oXygen-Projekt zur Verfügung stellen

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Quellenbeschreibung-mit-MEI#3]

**Comment by irmlindcapelle** [comment]
Lieber Benjamin,

ich sitze gerade etwas auf der Leitung. Hast Du mir mit dieser Mail mitgeteilt, dass Du die aktuellen Dateien in git abgelegt hast? 
Ich finde nämlich in meinem Repository keine Dateien mit einem Datum nach dem 5. September und auch nicht auf Pydio.

Ich wäre Dir für eine kurze Antwort, wie jetzt der Stand ist, dankbar. 

Herzliche Grüße
Irmlind
